#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FamilyMenu.Android.Resource", IsApplication=true)]

namespace FamilyMenu.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::FamilyMenu.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::FamilyMenu.Android.Resource.String.Hello;
			global::XLabs.Forms.Resource.Boolean.abc_action_bar_embed_tabs = global::FamilyMenu.Android.Resource.Boolean.abc_action_bar_embed_tabs;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::FamilyMenu.Android.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::FamilyMenu.Android.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::FamilyMenu.Android.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::FamilyMenu.Android.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::FamilyMenu.Android.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::FamilyMenu.Android.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::FamilyMenu.Android.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::FamilyMenu.Android.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::FamilyMenu.Android.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::FamilyMenu.Android.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::FamilyMenu.Android.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::FamilyMenu.Android.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Color.primary_text_default_material_dark = global::FamilyMenu.Android.Resource.Color.primary_text_default_material_dark;
			global::XLabs.Forms.Resource.Color.ripple_material_light = global::FamilyMenu.Android.Resource.Color.ripple_material_light;
			global::XLabs.Forms.Resource.Color.secondary_text_default_material_dark = global::FamilyMenu.Android.Resource.Color.secondary_text_default_material_dark;
			global::XLabs.Forms.Resource.Color.secondary_text_default_material_light = global::FamilyMenu.Android.Resource.Color.secondary_text_default_material_light;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::FamilyMenu.Android.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::FamilyMenu.Android.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::FamilyMenu.Android.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::FamilyMenu.Android.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::FamilyMenu.Android.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Dimension.notification_large_icon_height = global::FamilyMenu.Android.Resource.Dimension.notification_large_icon_height;
			global::XLabs.Forms.Resource.Dimension.notification_large_icon_width = global::FamilyMenu.Android.Resource.Dimension.notification_large_icon_width;
			global::XLabs.Forms.Resource.Dimension.notification_subtext_size = global::FamilyMenu.Android.Resource.Dimension.notification_subtext_size;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::FamilyMenu.Android.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::FamilyMenu.Android.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Drawable.notification_template_icon_bg = global::FamilyMenu.Android.Resource.Drawable.notification_template_icon_bg;
			global::XLabs.Forms.Resource.Id.action0 = global::FamilyMenu.Android.Resource.Id.action0;
			global::XLabs.Forms.Resource.Id.action_divider = global::FamilyMenu.Android.Resource.Id.action_divider;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::FamilyMenu.Android.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::FamilyMenu.Android.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.cancel_action = global::FamilyMenu.Android.Resource.Id.cancel_action;
			global::XLabs.Forms.Resource.Id.chronometer = global::FamilyMenu.Android.Resource.Id.chronometer;
			global::XLabs.Forms.Resource.Id.end_padder = global::FamilyMenu.Android.Resource.Id.end_padder;
			global::XLabs.Forms.Resource.Id.icon = global::FamilyMenu.Android.Resource.Id.icon;
			global::XLabs.Forms.Resource.Id.info = global::FamilyMenu.Android.Resource.Id.info;
			global::XLabs.Forms.Resource.Id.left_arrow = global::FamilyMenu.Android.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.line1 = global::FamilyMenu.Android.Resource.Id.line1;
			global::XLabs.Forms.Resource.Id.line3 = global::FamilyMenu.Android.Resource.Id.line3;
			global::XLabs.Forms.Resource.Id.media_actions = global::FamilyMenu.Android.Resource.Id.media_actions;
			global::XLabs.Forms.Resource.Id.normal = global::FamilyMenu.Android.Resource.Id.normal;
			global::XLabs.Forms.Resource.Id.right_arrow = global::FamilyMenu.Android.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.status_bar_latest_event_content = global::FamilyMenu.Android.Resource.Id.status_bar_latest_event_content;
			global::XLabs.Forms.Resource.Id.text = global::FamilyMenu.Android.Resource.Id.text;
			global::XLabs.Forms.Resource.Id.text2 = global::FamilyMenu.Android.Resource.Id.text2;
			global::XLabs.Forms.Resource.Id.time = global::FamilyMenu.Android.Resource.Id.time;
			global::XLabs.Forms.Resource.Id.title = global::FamilyMenu.Android.Resource.Id.title;
			global::XLabs.Forms.Resource.Integer.cancel_button_image_alpha = global::FamilyMenu.Android.Resource.Integer.cancel_button_image_alpha;
			global::XLabs.Forms.Resource.Integer.status_bar_notification_info_maxnum = global::FamilyMenu.Android.Resource.Integer.status_bar_notification_info_maxnum;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::FamilyMenu.Android.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::FamilyMenu.Android.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::FamilyMenu.Android.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::FamilyMenu.Android.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.notification_media_action = global::FamilyMenu.Android.Resource.Layout.notification_media_action;
			global::XLabs.Forms.Resource.Layout.notification_media_cancel_action = global::FamilyMenu.Android.Resource.Layout.notification_media_cancel_action;
			global::XLabs.Forms.Resource.Layout.notification_template_big_media = global::FamilyMenu.Android.Resource.Layout.notification_template_big_media;
			global::XLabs.Forms.Resource.Layout.notification_template_big_media_narrow = global::FamilyMenu.Android.Resource.Layout.notification_template_big_media_narrow;
			global::XLabs.Forms.Resource.Layout.notification_template_media = global::FamilyMenu.Android.Resource.Layout.notification_template_media;
			global::XLabs.Forms.Resource.Layout.notification_template_part_chronometer = global::FamilyMenu.Android.Resource.Layout.notification_template_part_chronometer;
			global::XLabs.Forms.Resource.Layout.notification_template_part_time = global::FamilyMenu.Android.Resource.Layout.notification_template_part_time;
			global::XLabs.Forms.Resource.Layout.week = global::FamilyMenu.Android.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::FamilyMenu.Android.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::FamilyMenu.Android.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::FamilyMenu.Android.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::FamilyMenu.Android.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::FamilyMenu.Android.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::FamilyMenu.Android.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::FamilyMenu.Android.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.String.status_bar_notification_info_overflow = global::FamilyMenu.Android.Resource.String.status_bar_notification_info_overflow;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::FamilyMenu.Android.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::FamilyMenu.Android.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::FamilyMenu.Android.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::FamilyMenu.Android.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::FamilyMenu.Android.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::FamilyMenu.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0b0000
			public const int abc_action_bar_embed_tabs = 2131427328;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_active_month_bg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int calendar_bg = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int calendar_divider = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int calendar_highlighted_day_bg = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int calendar_inactive_month_bg = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_selected_day_bg = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int calendar_selected_range_bg = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int calendar_text_active = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int calendar_text_inactive = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int calendar_text_selected = 2131099657;
			
			// aapt resource value: 0x7f060012
			public const int calendar_text_selector = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int calendar_text_unselectable = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int notification_action_color_filter = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int notification_icon_bg_color = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int notification_material_background_media_default_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int primary_text_default_material_dark = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int ripple_material_light = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int secondary_text_default_material_dark = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int secondary_text_default_material_light = 2131099665;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_day_headers_paddingbottom = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int calendar_month_title_bottommargin = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int calendar_month_topmargin = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int calendar_text_medium = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_text_small = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int compat_button_inset_horizontal_material = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int compat_button_inset_vertical_material = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int compat_button_padding_horizontal_material = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int compat_button_padding_vertical_material = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int compat_control_corner_material = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int notification_action_icon_size = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int notification_action_text_size = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_big_circle_margin = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int notification_content_margin_start = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int notification_large_icon_height = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_large_icon_width = 2131165202;
			
			// aapt resource value: 0x7f070007
			public const int notification_main_column_padding_top = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int notification_media_narrow_margin = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int notification_right_icon_size = 2131165203;
			
			// aapt resource value: 0x7f070005
			public const int notification_right_side_padding_top = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int notification_small_icon_background_padding = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int notification_small_icon_size_as_large = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int notification_subtext_size = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int notification_top_pad = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int notification_top_pad_large_text = 2131165208;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_left_blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow_right_blue = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int calendar_bg_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int JAP_MobileApplications57x57 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_action_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notification_bg_low = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_bg_low_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_bg_low_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_bg_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int notification_bg_normal_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int notification_icon_background = 2130837519;
			
			// aapt resource value: 0x7f020013
			public const int notification_template_icon_bg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int notification_template_icon_low_bg = 2130837524;
			
			// aapt resource value: 0x7f020010
			public const int notification_tile_bg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int notify_panel_notification_icon_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int splash = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001d
			public const int action0 = 2131296285;
			
			// aapt resource value: 0x7f09001a
			public const int action_container = 2131296282;
			
			// aapt resource value: 0x7f090021
			public const int action_divider = 2131296289;
			
			// aapt resource value: 0x7f09001b
			public const int action_image = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int action_text = 2131296284;
			
			// aapt resource value: 0x7f09002b
			public const int actions = 2131296299;
			
			// aapt resource value: 0x7f090010
			public const int async = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int blocking = 2131296273;
			
			// aapt resource value: 0x7f090019
			public const int calendar_grid = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int calendar_view = 2131296277;
			
			// aapt resource value: 0x7f09001e
			public const int cancel_action = 2131296286;
			
			// aapt resource value: 0x7f090026
			public const int chronometer = 2131296294;
			
			// aapt resource value: 0x7f09002d
			public const int end_padder = 2131296301;
			
			// aapt resource value: 0x7f090012
			public const int forever = 2131296274;
			
			// aapt resource value: 0x7f090000
			public const int ghost_view = 2131296256;
			
			// aapt resource value: 0x7f090028
			public const int icon = 2131296296;
			
			// aapt resource value: 0x7f09002c
			public const int icon_group = 2131296300;
			
			// aapt resource value: 0x7f090027
			public const int info = 2131296295;
			
			// aapt resource value: 0x7f090013
			public const int italic = 2131296275;
			
			// aapt resource value: 0x7f090017
			public const int left_arrow = 2131296279;
			
			// aapt resource value: 0x7f09000a
			public const int line1 = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int line3 = 2131296267;
			
			// aapt resource value: 0x7f090020
			public const int media_actions = 2131296288;
			
			// aapt resource value: 0x7f090018
			public const int myButton = 2131296280;
			
			// aapt resource value: 0x7f090014
			public const int normal = 2131296276;
			
			// aapt resource value: 0x7f09002a
			public const int notification_background = 2131296298;
			
			// aapt resource value: 0x7f090023
			public const int notification_main_column = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int notification_main_column_container = 2131296290;
			
			// aapt resource value: 0x7f090001
			public const int parent_matrix = 2131296257;
			
			// aapt resource value: 0x7f090016
			public const int right_arrow = 2131296278;
			
			// aapt resource value: 0x7f090029
			public const int right_icon = 2131296297;
			
			// aapt resource value: 0x7f090024
			public const int right_side = 2131296292;
			
			// aapt resource value: 0x7f090002
			public const int save_image_matrix = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int save_non_transition_alpha = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int save_scale_type = 2131296260;
			
			// aapt resource value: 0x7f09001f
			public const int status_bar_latest_event_content = 2131296287;
			
			// aapt resource value: 0x7f09000c
			public const int tag_transition_group = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int text = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int text2 = 2131296270;
			
			// aapt resource value: 0x7f090025
			public const int time = 2131296293;
			
			// aapt resource value: 0x7f09000f
			public const int title = 2131296271;
			
			// aapt resource value: 0x7f090005
			public const int transition_current_scene = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int transition_layout_save = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int transition_position = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int transition_scene_layoutid_cache = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int transition_transform = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int cancel_button_image_alpha = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int status_bar_notification_info_maxnum = 2131361793;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int month = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_action = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_action_tombstone = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_media_action = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_media_cancel_action = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_big_media = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_big_media_custom = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_big_media_narrow = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_big_media_narrow_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_custom_big = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_icon_group = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_lines_media = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_media = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_media_custom = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_part_chronometer = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_part_time = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int week = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int FamilyMenu = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int app_name = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int day_name_format = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int full_date_format = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int hello = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int invalid_date = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int library_name = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int month_name_format = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int status_bar_notification_info_overflow = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int CalendarCell = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int CalendarCell_CalendarDate = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int CalendarCell_DayHeader = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int CalendarTitle = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int TextAppearance_Compat_Notification = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int TextAppearance_Compat_Notification_Info = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Info_Media = 2131230724;
			
			// aapt resource value: 0x7f08000f
			public const int TextAppearance_Compat_Notification_Line2 = 2131230735;
			
			// aapt resource value: 0x7f080008
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int TextAppearance_Compat_Notification_Media = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int TextAppearance_Compat_Notification_Time = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Time_Media = 2131230726;
			
			// aapt resource value: 0x7f08000c
			public const int TextAppearance_Compat_Notification_Title = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Title_Media = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int Theme_Splash = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int Widget_Compat_NotificationActionContainer = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int Widget_Compat_NotificationActionText = 2131230734;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					0,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_fontStyle = 0;
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_fontWeight = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_font = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
